### ISSUE TITLE
不知道为什么又报错了

### ISSUE THREAD

**Issue by Sevyyy** [zlsun/yah3c#2]
错误如下：
[sevy@localhost home]$ cd ~
[sevy@localhost ~]$ sudo yah3c
0 - add a new user
1 - wangq248(enp4s0)
Your choice: 1
==> Sending EAPOL start
==> Got EAP Request for identity
==> Sending EAP response with identity = [wangq248]
==> Got EAP Request for MD5-Challenge
Traceback (most recent call last):
  File "/bin/yah3c", line 4, in <module>
    __import__('pkg_resources').run_script('yah3c==0.6', 'yah3c')
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.4/site-packages/yah3c-0.6-py3.4.egg/EGG-INFO/scripts/yah3c", line 4, in <module>
    __import__('pkg_resources').run_script('yah3c==0.6', 'yah3c')
  File "/usr/lib/python3.4/site-packages/yah3c-0.6-py3.4.egg/yah3c/yah3c.py", line 133, in main
  File "/usr/lib/python3.4/site-packages/yah3c-0.6-py3.4.egg/yah3c/yah3c.py", line 110, in start_yah3c
  File "/usr/lib/python3.4/site-packages/yah3c-0.6-py3.4.egg/yah3c/eapauth.py", line 182, in serve_forever
  File "/usr/lib/python3.4/site-packages/yah3c-0.6-py3.4.egg/yah3c/eapauth.py", line 166, in EAP_handler
  File "/usr/lib/python3.4/site-packages/yah3c-0.6-py3.4.egg/yah3c/eapauth.py", line 89, in send_response_md5
KeyError: 'md5_challenge'
[sevy@localhost ~]$

**Comment by zlsun** [comment]
抱歉，是这个 [commit](https://github.com/zlsun/yah3c/commit/a861ec1ae50751f6e1af9df84e72c559c4086920)  出bug了。

这学期我这边的 MD5 密码验证算法又改回之前的算法了，所以我在配置文件/etc/yah3c.conf里加了一个选项 md5_challenge，用于切换两种算法，可选的值有xor和md5，xor是原来的算法。

本来我是有写配置文件升级代码的，但情况处理得不全，我稍后再修复下这个bug。

在bug修复之前，你可以在 /etc/yah3c.conf 加上下面一行解决报错：
```
md5_challenge=xor # 或者md5，根据你那边的实际情况选择
```
